services:
  web:
    build: app/.
    ports:
      - 80:80

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: 
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

    